name: aoc_2024
description: Advent of Code 2024 solutions in Dart
version: 1.0.0
repository: https://github.com/dancarroll/aoc_2024

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
